#!/bin/sh
modprobe -r ansi_cprng
modprobe -r vmac
modprobe -r hmac
modprobe -r xcbc
modprobe -r seqiv
modprobe -r ccm
modprobe -r zlib
modprobe -r ecb
modprobe -r seed
modprobe -r rmd320
modprobe -r rmd256
modprobe -r rmd160
modprobe -r rmd128
modprobe -r cts
modprobe -r lzo
modprobe -r gcm
modprobe -r ghash_generic
modprobe -r salsa20_generic
modprobe -r salsa20_i586
modprobe -r cbc
modprobe -r camellia
modprobe -r pcbc
modprobe -r fcrypt
modprobe -r tgr192
modprobe -r anubis
modprobe -r wp512
modprobe -r khazad
modprobe -r tea
modprobe -r crc32c
modprobe -r michael_mic
modprobe -r arc4
modprobe -r cast6
modprobe -r cast5
modprobe -r deflate
modprobe -r sha512_generic
modprobe -r ctr
modprobe -r xts
modprobe -r lrw
modprobe -r aes_i586
modprobe -r aes_generic
modprobe -r serpent
modprobe -r twofish
modprobe -r blowfish
modprobe -r sha256_generic
modprobe -r md4
modprobe -r des_generic
modprobe -r sha1_generic

